config/routes.rb
Rails.application.routes.draw do

  root 'users#new'
  match 'users/create' => 'users#create', via: [:get, :post] 
  match 'refer-a-friend' => 'users#refer', via: [:get, :post]
  get '/leaders' => 'users#leaders'

end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :referrer, class_name: "User", foreign_key: "referrer_id"
  has_many :referrals, class_name: "User", foreign_key: "referrer_id"

  validates :email, :username, uniqueness: true
  validates :referral_code, uniqueness: true

  before_create :create_referral_code

  REFERRAL_STEPS = [
    {
        'count' => 5,
        "html" => "Coffee<br>Mug",
        "class" => "two",
        "image" =>  ActionController::Base.helpers.asset_path("refer/cream-tooltip@2x.png")
    },
    {
        'count' => 10,
        "html" => "Pizza",
        "class" => "three",
        "image" => ActionController::Base.helpers.asset_path("refer/truman@2x.png")
    },
    {
        'count' => 25,
        "html" => "Lunch with Walter",
        "class" => "four",
        "image" => ActionController::Base.helpers.asset_path("refer/winston@2x.png")
    },
    {
        'count' => 50,
        "html" => "Free<br>Wyncode",
        "class" => "five",
        "image" => ActionController::Base.helpers.asset_path("refer/blade-explain@2x.png")
    }
  ]

  def admin?
    self.role == 'admin'
  end

  private

    def create_referral_code
  	  #generate random hexadecimal referral code
      referral_code = SecureRandom.hex(5) 
      #find other user with the same referral code, if any
      @collision = User.find_by_referral_code(referral_code)
      #while other users with the same referral code are found
      while !@collision.nil?
    	#re-generate the referral code
    	  referral_code = SecureRandom.hex(5)
      end
      #unique referral code generated; save to current user
      self.referral_code = referral_code
    end

      ## Send email to registered user 
    def send_welcome_email
        UserMailer.signup_email(self) #removed .delay
    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :ref_to_cookies

  protected
  #method to save query string (?ref=) in cookies hash
  def ref_to_cookies
  	#if query string exists
  	if params[:ref]
  	  #if a User with the same referral code as in query string value found
      if !User.find_by_referral_code(params[:ref]).nil?
      	#save the value of the query string in the cookies hash
        cookies[:h_ref] = {value: params[:ref]}
      end
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  #only before new action, call skip_to_refer
  before_action :skip_to_refer, :only => :new

  def new
		@user = User.new
	end

	def create
		#find a User with the same email
		@user = User.find_by_email(:email)

		#if User does not exist
		if @user.nil?
			#create a new instance of User with email
			@user = User.new(user_params)
		
			#get the User with the same referral code as in the cookies hash
			@referred_by = User.find_by_referral_code(cookies[:h_ref])

			#if User found, set current User's referrer
			if !@referred_by.nil?
				@user.referrer = @referred_by
			end

			#save instance of current user
			@user.save

			# Sends email to user when user is created
      		UserMailer.signup_email(@user).deliver_now

			#delete referral code in cookies hash
			cookies.delete :h_ref

	  end
		#save current User's email in cookies hash for access in refer action
		cookies[:h_email] = {value: @user.email}
			
		#redirect to refer action (i.e. main referrable page)
		redirect_to '/refer-a-friend'			
	end

	def refer
		#retreive the current User's email from the cookies hash
		email = cookies[:h_email]

		#retreive current User
		@user = User.find_by_email(email)

		#if User not found
		if @user.nil?
			redirect_to root_path
		end
	end

	def skip_to_refer
		email = cookies[:h_email]
		if email and !User.find_by_email(email).nil?
		  redirect_to '/refer-a-friend'
		else
		  cookies.delete :h_email
		end 
	end

	def leaders
		@users = User.all
	end

	private
	def user_params
		params.require(:user).permit(:email, :username)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Referable</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/leaders.html.erb
<div class="container">
      <h1>Referrable Leaderboard</h1>
        <table class="table table-striped table-bordered table-condensed">
          <tbody>
            <tr>
             <th>User</th>
             <th>Referrals</th>
            </tr>
            <% @users.sort_by{|u| u.referrals.count }.reverse.each do |u| %>
          <tr>
            <td><%= u.username %></td>
            <td><%= u.referrals.count %></td>
          </tr>
            <% end %>
          </tbody>
        </table>
        <%= button_to "Back to Referable", refer_a_friend_path, :method => "get" %>
</div>

app/views/users/new.html.erb
<div class="container">
  <h1>Referable</h1>
  <%= form_for @user, url: {action: "create"} do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.submit "Spread the word!" %>
  <% end %>
</div>

app/views/users/refer.html.erb
<div class="container">
  <h1>Your Referable Page</h1>
  <p>Spread the word by sharing this link with your friends!</p>
  <strong><%= root_url %>?ref=<%= @user.referral_code %></strong>

  <h2>Referral Summary</h2>
  <% referrals_count = @user.referrals.count %>
  <% if referrals_count == 0 %>
  	<p><span>No</span> friends have joined...Yet!</p>
  <% else %>
  	<p>Total referrals: <strong><%= referrals_count %></strong> have joined!</p>
  <% end %>
  
  <%
    referrals_count = @user.referrals.count

    stops = User::REFERRAL_STEPS
  
    found = nil

    next_stop = nil

    stops.reverse_each { |stop|
        if stop["count"] <= referrals_count and !found
            stop["selected"] = true
            found = stop
            current_index = stops.index(stop)
             next_stop = stops.at(current_index + 1)
        else
            stop["selected"] = false
            next_stop = stops.at(0)
        end
    }
  %>

  <p>You are <strong><%= next_stop["count"]-referrals_count%></strong> referrals away from unlocking your next reward!</p>
  <%= button_to "Leaderboard", leaders_path, :method => "get" %>
</div>